import React,{useEffect,useState} from 'react';
import {api} from '../../services/api';
import {useSecureAuth} from '../../context/SecureAuthContext';

export const SecureAdminView:React.FC=()=>{
 const {user}=useSecureAuth(); const [apps,setApps]=useState<any[]>([]);const [companies,setCompanies]=useState<any[]>([]);const [users,setUsers]=useState<any[]>([]);const [error,setError]=useState('');
 const load=async()=>{try{const [a,c,u]=await Promise.all([api.applications(),api.companies(),api.users()]);setApps(a.applications);setCompanies(c.companies);setUsers(u.users)}catch(e:any){setError(e.message)}};
 useEffect(()=>{load()},[]);
 const review=async(id:number,status:string,tier?:string)=>{try{await api.review(id,status,tier);await load()}catch(e:any){setError(e.message)}};
 if(!user||!['SUPERADMIN','ADMIN'].includes(user.role))return <div className="p-6">No tiene permisos de administración.</div>;
 return <div className="space-y-8"><div><p className="text-red-500 font-black text-xs tracking-widest">ADMINISTRACIÓN REAL</p><h1 className="text-3xl font-black">Ibarbaso Business Club</h1><p className="text-slate-400">{apps.filter(a=>a.status==='PENDIENTE').length} solicitudes pendientes · {companies.length} empresas · {users.length} usuarios</p></div>{error&&<div className="bg-red-950/40 border border-red-700 p-3 rounded-xl">{error}</div>}<section><h2 className="text-xl font-bold mb-3">Solicitudes</h2><div className="space-y-3">{apps.length===0&&<div className="text-slate-500 border border-slate-800 rounded-2xl p-5">No hay solicitudes reales todavía.</div>}{apps.map(a=><div key={a.id} className="bg-[#0b152d] border border-[#1b3164] rounded-2xl p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold text-lg">{a.company_name}</h3><p className="text-sm text-slate-400">{a.contact_name} · {a.email} · {a.phone}</p><p className="text-sm mt-2">{a.motivation}</p><p className="text-xs text-slate-500 mt-2">Solicita {a.requested_tier} · Estado {a.status}</p></div>{a.status==='PENDIENTE'&&<div className="flex gap-2 items-start"><button onClick={()=>review(a.id,'APROBADO',a.requested_tier)} className="px-3 py-2 bg-emerald-700 rounded-lg font-bold text-sm">Aprobar</button><button onClick={()=>review(a.id,'RECHAZADO')} className="px-3 py-2 bg-red-700 rounded-lg font-bold text-sm">Rechazar</button></div>}</div></div>)}</div></section><section><h2 className="text-xl font-bold mb-3">Empresas verificadas</h2><div className="grid md:grid-cols-2 gap-3">{companies.map(c=><div key={c.id} className="bg-[#0b152d] border border-[#1b3164] rounded-2xl p-4"><b>{c.name}</b><div className="text-sm text-slate-400">{c.sector||'Sin sector'} · {c.membership_tier||'Sin nivel'} · {c.status}</div></div>)}</div></section></div>;
};
