import React,{useState} from 'react';
import {Lock,ShieldCheck,Eye,EyeOff} from 'lucide-react';

export const SetupAdminView:React.FC=()=>{
 const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState(''); const [show,setShow]=useState(false); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [done,setDone]=useState(false);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(password.length<12)return setError('La contraseña debe tener al menos 12 caracteres.');if(password!==confirm)return setError('Las contraseñas no coinciden.');setBusy(true);try{const r=await fetch('/api/setup/superadmin',{method:'POST',headers:{'Content-Type':'application/json','x-setup-token':String(import.meta.env.VITE_SETUP_TOKEN||'')},body:JSON.stringify({email:'sotoibarbaso@gmail.com',password,displayName:'Kroko'})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'La configuración inicial no está disponible.');setDone(true);setPassword('');setConfirm('');}catch(err:any){setError(err.message||'No se pudo crear el administrador.');}finally{setBusy(false)}};
 if(done)return <div className="min-h-screen bg-[#070d1e] text-white flex items-center justify-center p-5"><div className="w-full max-w-md bg-[#0b152d] border border-emerald-700/50 rounded-3xl p-8 text-center"><ShieldCheck className="w-12 h-12 mx-auto text-emerald-400 mb-4"/><h1 className="text-2xl font-black">Administrador creado</h1><p className="text-slate-300 mt-2">Kroko ya es SUPERADMIN.</p><a href="/" className="mt-6 inline-block w-full py-3 rounded-xl bg-red-600 font-bold">Ir al inicio de sesión</a></div></div>;
 return <div className="min-h-screen bg-[#070d1e] text-white flex items-center justify-center p-5"><div className="w-full max-w-md bg-[#0b152d] border border-[#1b3164] rounded-3xl p-7 shadow-2xl"><div className="w-12 h-12 bg-red-600/15 rounded-2xl flex items-center justify-center mb-5"><ShieldCheck className="text-red-500"/></div><h1 className="text-2xl font-black">Crear administrador</h1><p className="text-sm text-slate-400 mt-2 mb-6">Configuración inicial de Ibarbaso Business Club. Esta pantalla se desactiva cuando exista el primer SUPERADMIN.</p><form onSubmit={submit} className="space-y-4"><div><label className="text-xs font-bold text-slate-300">NOMBRE</label><input value="Kroko" disabled className="mt-1 w-full p-3 rounded-xl bg-[#070e20] border border-[#1d346b] text-slate-300"/></div><div><label className="text-xs font-bold text-slate-300">CORREO</label><input value="sotoibarbaso@gmail.com" disabled className="mt-1 w-full p-3 rounded-xl bg-[#070e20] border border-[#1d346b] text-slate-300"/></div><div><label className="text-xs font-bold text-slate-300">CONTRASEÑA</label><div className="relative"><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password" className="mt-1 w-full p-3 pr-12 rounded-xl bg-[#070e20] border border-[#1d346b] outline-none focus:border-red-500"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-4 text-slate-400">{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div><p className="text-[11px] text-slate-500 mt-1">Mínimo 12 caracteres.</p></div><div><label className="text-xs font-bold text-slate-300">REPETIR CONTRASEÑA</label><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password" className="mt-1 w-full p-3 rounded-xl bg-[#070e20] border border-[#1d346b] outline-none focus:border-red-500"/></div>{error&&<div className="text-sm text-red-300 bg-red-950/40 border border-red-700/40 p-3 rounded-xl">{error}</div>}<button disabled={busy} className="w-full py-3 rounded-xl bg-red-600 hover:bg-red-500 font-bold flex items-center justify-center gap-2 disabled:opacity-50"><Lock size={17}/>{busy?'Creando...':'Crear SUPERADMIN'}</button></form></div></div>;
};
